name: Build Windows application

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v6

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build application
        shell: cmd
        run: |
          cl /nologo /O2 /EHsc /DUNICODE /D_UNICODE /DWIN32 main.cpp /Fe:DiskSpaceTray.exe /link /SUBSYSTEM:WINDOWS

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: DiskSpaceTray
          path: DiskSpaceTray.exe
